[package]
name = "farder-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
farder-crypto = { workspace = true }
farder-protocol = { workspace = true }
quinn = "0.11"
rustls = { version = "0.23", features = ["ring"] }
rusqlite = { version = "0.32", features = ["bundled"] }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
x25519-dalek = { version = "2", features = ["static_secrets"] }

[dev-dependencies]
