[package]
name = "farder-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
farder-crypto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = "1"
anyhow = { workspace = true }

[dev-dependencies]
