[package]
name = "farder-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "farder_server"
path = "src/lib.rs"

[[bin]]
name = "farder-server"
path = "src/main.rs"

[dependencies]
farder-crypto = { workspace = true }
farder-protocol = { workspace = true }
quinn = "0.11"
bytes = "1"
rustls = { version = "0.23", features = ["ring"] }
rusqlite = { version = "0.31", features = ["bundled"] }
rcgen = "0.13"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }

[dev-dependencies]
tempfile = "3"
