import type { RegionDefinition } from "./types";

export const REGIONS: RegionDefinition[] = [
  {
    id: "main-bg",
    label: "Main background",
    hasText: false,
    hasImage: true,
    backgroundSelectors: ["body", "#root", ".app-shell", ".chat-panel"],
    textSelectors: [],
  },
  {
    id: "channel-sidebar",
    label: "Channel sidebar",
    hasText: true,
    hasImage: true,
    backgroundSelectors: [".channel-sidebar"],
    textSelectors: [".channel-sidebar", ".channel-name", ".channel-category"],
  },
  {
    id: "server-strip",
    label: "Server strip",
    hasText: false,
    hasImage: true,
    backgroundSelectors: [".server-strip"],
    textSelectors: [],
  },
  {
    id: "member-sidebar",
    label: "Member sidebar",
    hasText: true,
    hasImage: true,
    backgroundSelectors: [".member-sidebar"],
    textSelectors: [".member-sidebar", ".member-name"],
  },
  {
    id: "title-bars",
    label: "Title bars",
    hasText: true,
    hasImage: false,
    backgroundSelectors: [
      ".title-bar",
      ".connect-dialog-titlebar",
      ".modal-titlebar",
    ],
    textSelectors: [".title-bar", ".connect-dialog-titlebar", ".modal-titlebar"],
  },
  {
    id: "message-bubble",
    label: "Message bubble",
    hasText: true,
    hasImage: true,
    backgroundSelectors: [".message", ".message-content"],
    textSelectors: [".message", ".message-content"],
  },
  {
    id: "message-hover",
    label: "Message hover",
    hasText: false,
    hasImage: false,
    backgroundSelectors: [".message:hover"],
    textSelectors: [],
  },
  {
    id: "buttons",
    label: "Buttons",
    hasText: true,
    hasImage: false,
    backgroundSelectors: [".xp-button"],
    textSelectors: [".xp-button"],
  },
  {
    id: "input-field",
    label: "Input field",
    hasText: true,
    hasImage: false,
    backgroundSelectors: [".message-input", "input[type=\"text\"]", "textarea"],
    textSelectors: [".message-input", "input[type=\"text\"]", "textarea"],
  },
  {
    id: "modal-bg",
    label: "Modal background",
    hasText: false,
    hasImage: true,
    backgroundSelectors: [".connect-screen", ".modal", ".dialog-body"],
    textSelectors: [],
  },
  {
    id: "scrollbars",
    label: "Scrollbars",
    hasText: false,
    hasImage: false,
    backgroundSelectors: ["::-webkit-scrollbar-thumb"],
    textSelectors: [],
  },
  {
    id: "accent",
    label: "Accent (active / selected)",
    hasText: false,
    hasImage: false,
    backgroundSelectors: [],
    textSelectors: [],
    accentVariable: "--xp-blue",
  },
];

export const REGIONS_BY_ID: Map<string, RegionDefinition> = new Map(
  REGIONS.map((r) => [r.id, r]),
);
